module.exports = [
    'im going to drink some coffee and then let my cat lick the mug and see if he gets any fucking coffee',
    'i am a veritable god of pelicans',
    'when you\'re watching a crime documentary and they zoom in on a knife and you\'re like "that\'s a fine knife"',
    'im a wild man. im a crazy person. im wild. im crazy. i have a problem',
    'when the phone rings, im like oh shit, someone is calling me',
    'i can\'t believe there is a fucking show called the bachelor. shut the fuck up',
    'honestly tho im not going to be able to keep up with this shit. im going to be the guy that you get a text from like "OMG I FOUND A NEW THING CALLED TWITTER!! WHERE ARE MY ANTIDEPRESSANTS!!!!!!!"',
    'everybody shut the fuck up. sims 5: tokyo drift',
    'current mood: [masturbating furiousy]',
    '"im gonna eat this whole bag of dicks" -me',
    'when jesus was born they put him in a manger which is a small feeding trough for animals. which is ironic because he was really a horse',
    'people are always like "oh why did you go to the bathroom today" and im like "well why did you not go to the bathroom today"',
    'i bought a bunch of weird old cheese at an antique store and now my fridge smells like old people and i\'m not sure what to do',
    'if you have a tiny dick you feel like the biggest loser ever but if you don\'t have a tiny dick you feel like the biggest loser ever too',
    'the more people that post about their problems on facebook the more likely they are to be in a pelican gang',
    'pokemon card: lets give this guy the power to just rip his own arm off and throw it at the enemy',
    'the internet is just a bunch of people yelling at each other about how they think that the earth is the center of the universe',
    'i wish i could just change my name to asshole jenkins the fourth',
    `me: *clumsily stumbles into the kitchen*\n\
    dad: what the hell are you doing\n\
    me: sorry i dropped my spoon\n\
    dad: there's a fork right next to you\n\
    me: but i like the spoon\n\
    dad: that's such a weird thing to like\n\
    me: *starts crying and runs upstairs*`,
    'i want to be a sky diver. i want to jump out of a plane and every time i\'m in midair i\'m like "oh i\'m gonna die"',
    'i make a very good caesar salad if you\'re ever in need',
    'i\'m pretty sure i\'m the most effective and efficient comedian alive',
    'if you are a cop and you want to know if someone is a serial killer look at their hands. if they have nail polish get the fuck out of there',
    'i just paid my rent. time to just straight up murder someone and go to jail lmao',
    `giant group of cats: hey guys guess what we're all cats now\n\ \n\
    one cat: yeah, let's do this. this is gonna be great`,
    'i was thinking about making a cologne that makes you smell like a wrestler',
    'i hope that when i die a bunch of frogs come out of my mouth',
    'i made an omelette and cut it into pieces but then i put it back together and it looked like a shitty jigsaw puzzle',
    'if i have a really bad day i go to a fast food place and order a bunch of things on the dollar menu and then leave without paying.',
    'if you could just take a moment to imagine how stupid it is that we have a god',
    'i want to have a bunch of kids and then force them to all move to tokyo. i dont even give a shit',
    'i want to make a new law where if you eat 5+ pieces of candy corn in a row your stomach immediately explodes',
    'i keep thinking about the time i had to lie on a table and a lady put a giant metal clamp on me so she could staple my dick shut',
    `new year's resolution: don't do cocaine\n\ \n\

    january 2nd: ok i did cocaine`,
    'dear diary i have taken up smoking cigarettes i\'m adorable',
    'for some reason i always assume that every white person has to be a witch',
    'someone should invent a device that will jizz on your back when you\'re about to be punched in the back of the head',
    'after this im going to go back to my underpants fort and read a book',
    'there\'s no reason to be embarrassed about being a grown man with a bunch of underpants. you do you man',
    'i think a lot of people would be down to get a tattoo of their family tree if the branches all came out of the same asshole',
    'i wonder if early bird gets told to go fuck himself every morning',
    'my parents were always in a bad mood during the week but i could always tell when they were happy because they\'d be in a bad mood on the weekend too',
    'just going to walk around forever and pretend im a fish',
    'the spider is THE MOST GENEROUS CREATURE ON THIS PLANET. FUCK YOU',
    'in the future when we\'re all jacked in to the matrix like a bunch of cables im gonna say "yo you guys remember when we had to use our arms for mouse movements"',
    'i wanna go to the zoo and punch a lion in the face and have it chase me around the zoo',
    'i will die right after i finish this tweet just to see if i have another life in a parallel universe',
    'the most popular physical activity in heaven is a game called "don\'t step on the turtles"',
    'what would you do if you woke up as a pokemon. it would be like "[puking noises]" lmao',
    'i just talked to the guy at the grocery store that sells produce and i asked him if he has any peaches and he said "i\'m sorry"',
    'i\'ve never really had a hard time sleeping. i usually just sleep on the floor of a stranger\'s house and then when they wake up i tell them im a butterfly',
    'i like to go up to cops and ask them if they\'ve ever had a dream about a house that has no doors. and then just walk away',
    'i accidentally cut my finger off the other day with a can opener. and then i put it on a table and said "your turn."',
    'i don\'t want to be a loudmouth but i\'m curious. are there any quietmouths in the room',
    'if you have a pet dog and you\'re watching dog movies, you might as well just ask the dog "hey do you like this movie"',
    `real friends: do you wanna come over tomorrow and watch movies\n\
    me: i'm good i think i'll just go home and stare at a wall\n\
    real friends: ok`,
    'old people be like "grandkids are great. one time i used my wheelchair to go to space"',
    'if i was going to name a toothbrush i would call it "the toothbrush of wisdom"',
    'i want a nickname that rhymes with "pussy" but isn\'t "pussy"',
    'theres a new show on tlc called "the man who eats his wife" i hope it\'s a documentary',
    `#aboutlastnight\n\
    a guy on the street saw my dick on the sidewalk and asked me if i had been circumcised`,
    'the most important thing about being a man is your ability to take a shit while standing up',
    '"hey you gotta help me my leg is stuck in this asshole" - me at the dmv',
    'my doctor told me i have a 50/50 chance of having a heart attack in the next 10 years... i would have felt better about those odds if i wasn\'t sure he was just saying that to make me have sex with him',
    'i wanna fuck a ghost i wanna fuck a ghost i wanna fuck a ghost i wanna fuck a gh',
    'movie about a guy who works at a movie theater and gets crushed to death by a projector',
    'i got a tattoo of a sloth on my arm so i can go to the bathroom and look at my phone in peace!!!!',
    'i was just driving home and thought "wow im driving down a real road. holy shit lol"',
    'im pretty sure it\'s illegal to not have a catchphrase',
    '"i\'m here to tell you that you can\'t be passive about your own life. you\'ve gotta get involved. you\'ve gotta go to mcdonalds." -- from a fortune cookie',
    '"you know what, if you hit me with that shovel one more time i\'m gonna hit myself with it!!!"',
    'if you see a dog sitting on a sofa and he looks like he\'s about to start crying you should probably not sit next to him',
    'at cvs loudly knocking down the flu shot display: hey alexa play some limp bizkit',
    'i\'d like to be a pirate but not get eaten by a shark in the first like 2 minutes of the movie',
    'i used to have problems with my neighbors. i don\'t know if you know this, but you can use a sock puppet as a way to masturbate',
    'imagine a murderer who gets a liver transplant from a really nice dude. he ends up becoming a really nice dude too.',
    '"stop having a good time, everyone is hungry and we\'re out of food" - me at the beach on vacation waiting for uber eats',
    'imagine a big restaurant that serves your family and friends. but it puts your family and friends in jail after',
    'i would rather have a bag of groceries fall on my head than get into a discussion about politics',
    'maybe i\'ll start a podcast called "the milky way" where i tell scientists to go fuck themselves',
    'i bet theres a space ship called the serenity that has a bunch of british people on it that are like "oh my god this is fantastic"',
    'the best thing about having a girlfriend is that you have an excuse to order $40 worth of pizza and then hide it',
    'i have so much self-hatred that i\'m literally sitting here putting ketchup on my plate and then eating that',
    'i feel like a lot of things in life are overrated. ex: if youre in the woods and you find a person chained to a tree, nobody thinks to themselves "wow i must free this guy!"',
    'i told my psychiatrist i was hearing voices in my head. he said who\'s talking. i said god and he said where\'s god\'s office',
    `supreme court judge: you\'re under arrest for being a dog\n\
dog: fffuck`,
    'if i\'m ever carrying around a bag of candy and you\'re like TALKING TO ME I\'m just gonna be like sorry i have to eat this entire bag of candy',
    'imagine if you could hear a dog laughing',
    'the only way to make a bad day better is to get a piece of mail in the mail',
    'im in a long distance relationship and i know she\'s cheating on me but im ordering mcdonalds rn so who\'s really winning',
    'i love my best friend but he smells like shit. i mean that in the best way possible',
    'never trust a dog to babysit your children. ur welcome',
    'i took a 5 hour nap and when i woke up i was still tired so i took a 5 hour nap again and when i woke up i was still tired. shit',
    'i had 3 pepsi max\'s today and i feel like i can jump into space',
    'what the hell is weird al doing. he\'s going to take over the world with polka. i\'m not joking. this is a national security issue',
    'what\'s the deal with hippopotamus. fucking piece of shit',
    'i\'m getting my beard worked on right now and my barber is also my therapist and he\'s telling me how to fix my problems and i\'m like "yeah that\'s good advice but i\'m not gonna listen to you because you\'re my barber and i don\'t want to fuck up my beard"',
    'i bet you think your car is safe but it\'s not. i\'m gonna put a frog in it',
    'the only reason i enjoy hot dogs is because they make it look like you\'re eating the bottom of a shoe',
    'i can\'t tell if i\'m really happy or if i\'m just getting used to being an asshole',
    'when my parents told me they were bringing home a new baby brother i was like "yeah thats great but can u bring me home a mcdouble and fries"',
    'i wanna get a tattoo of a guy in a cowboy hat that says "there are no words"',
    'i was just reading a book about the history of the bathroom and i was like "oh wow this is a lot of info i did not need to know about the bathroom"',
    'theres this guy i know who always acts like he knows everything well for his birthday i got him a card that said "i know everything"',
    'you ever think ab how much it must suck to be a gummy worm',
    'first day of a new job as a mechanic and you realize the shop is filled with fucking snakes that you can\'t kill',
    'ive always thought that if i were a ghost i would live in a cave and be really good friends with the local raccoons',
    'my therapist told me i\'m depressed but i\'m not not not not not not not not not not not not not depressed',
    'the kids in my high school class were all really good at math except for me. i was really good at being sad',
    'man learns to play guitar but only knows how to play the opening to "we will rock you" and gets that tattooed on his wrist'
]